"""Per-order CFN template parts — Parameters, Resources, UserData.

Pure data builders called by `CfnService.render_template`. Splitting them
out keeps the service file thin and lets unit tests target each block.
"""

from typing import Final

# Latest Amazon Linux 2023 x86_64 AMI in any region. CFN resolves this SSM
# parameter against `--region` at deploy time, so the template is region-portable
# without a Mappings table that would go stale every AMI revision.
AMI_SSM_PARAMETER: Final[str] = (
    "{{resolve:ssm:/aws/service/ami-amazon-linux-latest/al2023-ami-kernel-default-x86_64}}"
)
EMS_SERVICES: Final[tuple[str, ...]] = (
    "ems-device-api",
    "ems-hmi",
    "ems-industrial-gateway",
)

# Six vendor-token parameters the operator pastes at create-stack time.
# The Lambda custom resources in src/cfn/persistence/ use these tokens
# to call vendor REST APIs (Tiger Cloud + Neo4j Aura) and provision
# instances. Operators no longer paste raw connection strings — those
# are generated by the Lambdas and stored in Secrets Manager. NoEcho
# keeps tokens out of the Console UI.
VENDOR_TOKEN_PARAMETERS: Final[tuple[tuple[str, str], ...]] = (
    (
        "TigerCloudAccessKey",
        "Tiger Cloud access key (Tiger Console > Settings > API Keys).",
    ),
    (
        "TigerCloudSecretKey",
        "Tiger Cloud secret key (paired with access key).",
    ),
    (
        "TigerCloudProjectId",
        "Tiger Cloud project id (UUID shown on the Projects page).",
    ),
    (
        "Neo4jAuraClientId",
        "Neo4j Aura OAuth2 client id (Aura Console > Account > API Keys).",
    ),
    (
        "Neo4jAuraClientSecret",
        "Neo4j Aura OAuth2 client secret (paired with client id).",
    ),
    (
        "Neo4jAuraTenantId",
        "Neo4j Aura tenant id (Aura Console > Account > Tenants).",
    ),
)


def vendor_token_parameters() -> dict[str, object]:
    """Six required no-default NoEcho String parameters for vendor REST API auth."""
    return {
        name: {
            "Type": "String",
            "NoEcho": True,
            "MinLength": 1,
            "Description": description,
        }
        for name, description in VENDOR_TOKEN_PARAMETERS
    }


def network_resources() -> dict[str, object]:
    """Tiny VPC + public subnet so the operator launches without parameters."""
    return {
        "EmsVpc": {
            "Type": "AWS::EC2::VPC",
            "Properties": {
                "CidrBlock": "10.0.0.0/16",
                "EnableDnsSupport": True,
                "EnableDnsHostnames": True,
            },
        },
        "EmsInternetGateway": {"Type": "AWS::EC2::InternetGateway"},
        "EmsVpcGatewayAttachment": {
            "Type": "AWS::EC2::VPCGatewayAttachment",
            "Properties": {
                "VpcId": {"Ref": "EmsVpc"},
                "InternetGatewayId": {"Ref": "EmsInternetGateway"},
            },
        },
        "EmsSubnet": {
            "Type": "AWS::EC2::Subnet",
            "Properties": {
                "VpcId": {"Ref": "EmsVpc"},
                "CidrBlock": "10.0.0.0/24",
                "MapPublicIpOnLaunch": True,
            },
        },
        "EmsRouteTable": {
            "Type": "AWS::EC2::RouteTable",
            "Properties": {"VpcId": {"Ref": "EmsVpc"}},
        },
        "EmsDefaultRoute": {
            "Type": "AWS::EC2::Route",
            "DependsOn": "EmsVpcGatewayAttachment",
            "Properties": {
                "RouteTableId": {"Ref": "EmsRouteTable"},
                "DestinationCidrBlock": "0.0.0.0/0",
                "GatewayId": {"Ref": "EmsInternetGateway"},
            },
        },
        "EmsSubnetRouteTableAssociation": {
            "Type": "AWS::EC2::SubnetRouteTableAssociation",
            "Properties": {
                "SubnetId": {"Ref": "EmsSubnet"},
                "RouteTableId": {"Ref": "EmsRouteTable"},
            },
        },
        "EmsSecurityGroup": {
            "Type": "AWS::EC2::SecurityGroup",
            "Properties": {
                "GroupDescription": "ARCNODE EMS HMI inbound",
                "VpcId": {"Ref": "EmsVpc"},
                "SecurityGroupIngress": [
                    {
                        "IpProtocol": "tcp",
                        "FromPort": 80,
                        "ToPort": 80,
                        "CidrIp": "0.0.0.0/0",
                    }
                ],
            },
        },
    }


def iam_resources(*, short: str) -> dict[str, object]:
    """Instance role with S3 GetObject (DTM fetch) + SecretsManager read for persistence."""
    return {
        "EmsInstanceRole": {
            "Type": "AWS::IAM::Role",
            "Properties": {
                "AssumeRolePolicyDocument": {
                    "Version": "2012-10-17",
                    "Statement": [
                        {
                            "Effect": "Allow",
                            "Principal": {"Service": "ec2.amazonaws.com"},
                            "Action": "sts:AssumeRole",
                        }
                    ],
                },
                "Policies": [
                    {
                        "PolicyName": f"arcnode-{short}-dtm-read",
                        "PolicyDocument": {
                            "Version": "2012-10-17",
                            "Statement": [
                                {
                                    "Effect": "Allow",
                                    "Action": "s3:GetObject",
                                    "Resource": "*",
                                }
                            ],
                        },
                    },
                    {
                        "PolicyName": f"arcnode-{short}-secrets-read",
                        "PolicyDocument": {
                            "Version": "2012-10-17",
                            "Statement": [
                                {
                                    "Effect": "Allow",
                                    "Action": "secretsmanager:GetSecretValue",
                                    "Resource": {
                                        "Fn::Sub": "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:ems/*"
                                    },
                                }
                            ],
                        },
                    },
                ],
            },
        },
        "EmsInstanceProfile": {
            "Type": "AWS::IAM::InstanceProfile",
            "Properties": {"Roles": [{"Ref": "EmsInstanceRole"}]},
        },
    }


PERSISTENCE_SECRET_SLOTS: Final[tuple[str, ...]] = (
    "aurora-document",
    "aurora-vector",
    "tiger",
    "neo4j-aura",
)


def build_userdata(*, deployment_uuid: str, dtm_url: str, ems_mode: str) -> str:
    """UserData: write deployment env, fetch persistence secrets, fetch DTM.

    Each persistence secret was created at stack-create time by the
    Aurora-bootstrap / Tiger-provisioner / Aura-provisioner Lambdas. The
    EC2 instance fetches them via the AWS CLI (preinstalled on AL2023)
    using the instance profile's secrets-read policy granted in
    iam_resources(). Secrets are written to /opt/arcnode/<name>.url so
    docker-compose can source them via env_file: directives.
    """
    fetch_lines = "\n".join(
        f'aws secretsmanager get-secret-value --secret-id "ems/{deployment_uuid}/persistence/{slot}" '
        f"--query SecretString --output text > /opt/arcnode/{slot}.url"
        for slot in PERSISTENCE_SECRET_SLOTS
    )
    return (
        "#!/bin/bash\n"
        "set -euo pipefail\n"
        "mkdir -p /opt/arcnode\n"
        "cat > /opt/arcnode/deployment.env <<ENV\n"
        f"DEPLOYMENT_UUID={deployment_uuid}\n"
        f"DTM_URL={dtm_url}\n"
        f"EMS_MODE={ems_mode}\n"
        "ENV\n"
        "# Fetch persistence connection strings from Secrets Manager.\n"
        f"{fetch_lines}\n"
        "# Fetch the Device Topology Manifest via presigned URL (valid 24h).\n"
        f"curl -fsSL '{dtm_url}' -o /opt/arcnode/dtm.json || "
        "echo 'DTM fetch failed; populate /opt/arcnode/dtm.json manually'\n"
        "touch /opt/arcnode/userdata.done\n"
    )
