"""CFN Secrets Manager entries for v1 broker + human auth.

Variant-agnostic — both commercial and defense get these (the broker runs
File RBAC in every deployment). Two kinds:

  machine creds (random, generated by CFN):
    mqtt-gateway-password   gateway → broker
    mqtt-operator-password  HMI operator role broker cred (device-api hands out)
    mqtt-viewer-password    HMI viewer role broker cred (device-api hands out)
    auth-jwt-secret         device-api HS256 session-token signing key

  human creds (customer-set plaintext, pasted as NoEcho params):
    auth-operator-pw        operator login password
    auth-viewer-pw          viewer login password

EC2 UserData fetches each by slot name into secrets.env (services consume) and,
for the 3 mqtt passwords, also writes them into credentials.xml (broker reads).
See AUTH_SLOTS in cfn_resources.py for the slot→env mapping.
"""

# Chars excluded from generated secrets so the values are safe to drop into
# XML element content (credentials.xml), a shell heredoc, and KEY=value lines
# in secrets.env: XML specials < > &, quotes, and shell-active $ ` \ / @.
_EXCLUDE_CHARS = "\"'@/\\<>&$`"


def _generated_secret(slot: str, description: str) -> dict:
    """A 32-char random secret materialized by CFN (no plaintext in template)."""
    return {
        "Type": "AWS::SecretsManager::Secret",
        "Properties": {
            "Name": {"Fn::Sub": f"arcnode-ems-${{AWS::StackName}}/{slot}"},
            "Description": description,
            "GenerateSecretString": {
                "PasswordLength": 32,
                "ExcludeCharacters": _EXCLUDE_CHARS,
            },
        },
    }


def auth_machine_secrets() -> dict[str, dict]:
    """Five CFN-generated random secrets: 4 broker passwords + JWT signing key."""
    return {
        "MqttGatewayPasswordSecret": _generated_secret(
            "mqtt-gateway-password", "Broker File-RBAC password for arcnode_gateway."
        ),
        "MqttOperatorPasswordSecret": _generated_secret(
            "mqtt-operator-password", "Broker File-RBAC password for arcnode_operator."
        ),
        "MqttViewerPasswordSecret": _generated_secret(
            "mqtt-viewer-password", "Broker File-RBAC password for arcnode_viewer."
        ),
        # device-api connects to publish system/topology_changed (the gateway
        # subscribes to it to hot-reload topology). Its own File-RBAC identity.
        "MqttDeviceApiPasswordSecret": _generated_secret(
            "mqtt-device-api-password",
            "Broker File-RBAC password for arcnode_device_api.",
        ),
        # telemetry-writer subscribes measurements → persists to the timeseries
        # DB. Dedicated service identity (not the browser-distributed viewer cred).
        "MqttTelemetryWriterPasswordSecret": _generated_secret(
            "mqtt-telemetry-writer-password",
            "Broker File-RBAC password for arcnode_telemetry_writer.",
        ),
        "AuthJwtSecret": _generated_secret(
            "auth-jwt-secret", "device-api HS256 session-token signing key."
        ),
    }


def _param_secret(slot: str, param: str, description: str) -> dict:
    """A secret whose value is a !Ref to a NoEcho param (customer-pasted)."""
    return {
        "Type": "AWS::SecretsManager::Secret",
        "Properties": {
            "Name": {"Fn::Sub": f"arcnode-ems-${{AWS::StackName}}/{slot}"},
            "Description": description,
            "SecretString": {"Ref": param},
        },
    }


def auth_human_secrets() -> dict[str, dict]:
    """Two secrets sourced from the customer-set login-password params."""
    return {
        "AuthOperatorPwSecret": _param_secret(
            "auth-operator-pw", "AuthOperatorPw", "Operator login password (plaintext)."
        ),
        "AuthViewerPwSecret": _param_secret(
            "auth-viewer-pw", "AuthViewerPw", "Viewer login password (plaintext)."
        ),
    }


def auth_human_parameters() -> dict[str, dict]:
    """Two NoEcho String params — the customer's operator + viewer login pws.

    device-api bcrypt-hashes these at boot (it never stores plaintext at rest
    beyond secrets.env). NoEcho keeps them out of the Console + audit logs.
    """
    return {
        "AuthOperatorPw": {
            "Type": "String",
            "NoEcho": True,
            "MinLength": 1,
            "Description": "Operator login password (HMI dispatch role).",
        },
        "AuthViewerPw": {
            "Type": "String",
            "NoEcho": True,
            "MinLength": 1,
            "Description": "Viewer login password (HMI read-only role).",
        },
    }
