"""CFN Secrets Manager entries for v1 broker + human auth.

Variant-agnostic — both commercial and defense get these (the broker runs
File RBAC in every deployment). Three kinds:

  machine creds (random, generated by CFN):
    mqtt-gateway-password         gateway → broker
    mqtt-operator-password        HMI operator role broker cred (device-api hands out)
    mqtt-viewer-password          HMI viewer role broker cred (device-api hands out)
    mqtt-device-api-password      device-api → broker (system/topology_changed)
    mqtt-telemetry-writer-password  telemetry-writer → broker (subscribes measurements)
    mqtt-der-control-api-password   der-control-api → broker (der_dispatch setpoints)
    auth-jwt-secret               device-api HS256 session-token signing key

  human creds (customer-set plaintext, pasted as NoEcho params):
    auth-operator-pw        operator login password
    auth-viewer-pw          viewer login password

  ops-populated placeholder (static content, no customer param, no random
  generation — someone with AWS console/CLI access overwrites it):
    der-control-truststore-pem   der-control-ingress's mTLS trust anchor
                                 (the DERMS utility's CA bundle). Per-
                                 integration, not per-order — not part of
                                 ConfiguratorPayload.

EC2 UserData fetches each by slot name into secrets.env (services consume) and,
for the mqtt passwords, also writes them into credentials.xml (broker reads).
The truststore is the one exception — it's a PEM bundle, not a KEY=VALUE line,
so UserData writes it straight to a file instead. See AUTH_SLOTS in
cfn_resources.py for the slot→env mapping.
"""

# Chars excluded from generated secrets so the values are safe to drop into
# XML element content (credentials.xml), a shell heredoc, and KEY=value lines
# in secrets.env: XML specials < > &, quotes, and shell-active $ ` \ / @.
_EXCLUDE_CHARS = "\"'@/\\<>&$`"


def _generated_secret(slot: str, description: str) -> dict:
    """A 32-char random secret materialized by CFN (no plaintext in template)."""
    return {
        "Type": "AWS::SecretsManager::Secret",
        "Properties": {
            "Name": {"Fn::Sub": f"arcnode-ems-${{AWS::StackName}}/{slot}"},
            "Description": description,
            "GenerateSecretString": {
                "PasswordLength": 32,
                "ExcludeCharacters": _EXCLUDE_CHARS,
            },
        },
    }


def auth_machine_secrets() -> dict[str, dict]:
    """CFN-generated random secrets: 5 broker passwords + JWT signing key."""
    return {
        "MqttGatewayPasswordSecret": _generated_secret(
            "mqtt-gateway-password", "Broker File-RBAC password for arcnode_gateway."
        ),
        "MqttOperatorPasswordSecret": _generated_secret(
            "mqtt-operator-password", "Broker File-RBAC password for arcnode_operator."
        ),
        "MqttViewerPasswordSecret": _generated_secret(
            "mqtt-viewer-password", "Broker File-RBAC password for arcnode_viewer."
        ),
        # device-api connects to publish system/topology_changed (the gateway
        # subscribes to it to hot-reload topology). Its own File-RBAC identity.
        "MqttDeviceApiPasswordSecret": _generated_secret(
            "mqtt-device-api-password",
            "Broker File-RBAC password for arcnode_device_api.",
        ),
        # telemetry-writer subscribes measurements → persists to the timeseries
        # DB. Dedicated service identity (not the browser-distributed viewer cred).
        "MqttTelemetryWriterPasswordSecret": _generated_secret(
            "mqtt-telemetry-writer-password",
            "Broker File-RBAC password for arcnode_telemetry_writer.",
        ),
        # der-control-api publishes DERControl setpoints as measurements on the
        # der_dispatch singleton device. PUBLISH-only, scoped to that device —
        # tighter than the gateway (which publishes all measurements/#).
        "MqttDerControlApiPasswordSecret": _generated_secret(
            "mqtt-der-control-api-password",
            "Broker File-RBAC password for arcnode_der_control_api.",
        ),
        "AuthJwtSecret": _generated_secret(
            "auth-jwt-secret", "device-api HS256 session-token signing key."
        ),
    }


def _param_secret(slot: str, param: str, description: str) -> dict:
    """A secret whose value is a !Ref to a NoEcho param (customer-pasted)."""
    return {
        "Type": "AWS::SecretsManager::Secret",
        "Properties": {
            "Name": {"Fn::Sub": f"arcnode-ems-${{AWS::StackName}}/{slot}"},
            "Description": description,
            "SecretString": {"Ref": param},
        },
    }


def auth_human_secrets() -> dict[str, dict]:
    """Two secrets sourced from the customer-set login-password params."""
    return {
        "AuthOperatorPwSecret": _param_secret(
            "auth-operator-pw", "AuthOperatorPw", "Operator login password (plaintext)."
        ),
        "AuthViewerPwSecret": _param_secret(
            "auth-viewer-pw", "AuthViewerPw", "Viewer login password (plaintext)."
        ),
    }


# Throwaway self-signed cert (CN says exactly what it is) — a *syntactically
# valid* PEM so nginx's `ssl_client_certificate` loads cleanly and the
# container comes up healthy on every fresh deploy, instead of crash-looping
# on a fresh install until ops gets around to it. It trusts nothing real, so
# every DERMS connection attempt fails cert verification (fail-closed) until
# ops overwrites the secret with the actual utility CA bundle. Generated
# once with `openssl req -x509 -newkey rsa:2048 -nodes -days 3650`; never
# needs regenerating (nobody ever holds its private key on purpose).
_PLACEHOLDER_TRUSTSTORE_PEM = """-----BEGIN CERTIFICATE-----
MIIDZzCCAk+gAwIBAgIUbsqPjkyVOOsBxSE/hmeQnwCflNIwDQYJKoZIhvcNAQEL
BQAwQzFBMD8GA1UEAww4YXJjbm9kZS1kZXItY29udHJvbC10cnVzdHN0b3JlLVBM
QUNFSE9MREVSLW5vdC1hLXJlYWwtY2EwHhcNMjYwOTEwMjIyOTA0WhcNMzYwOTA3
MjIyOTA0WjBDMUEwPwYDVQQDDDhhcmNub2RlLWRlci1jb250cm9sLXRydXN0c3Rv
cmUtUExBQ0VIT0xERVItbm90LWEtcmVhbC1jYTCCASIwDQYJKoZIhvcNAQEBBQAD
ggEPADCCAQoCggEBALcqsvobHOCtafVMkqi7lZS9DluSJD8fY5FlQxj6VyflIpXO
L/HZEiyV2S41Xw94ZVrWnuAoVkX0djnWn2gwCOYdHH66V7hge/YZQgm/F4xPDYKQ
dDJTywTiCePIYrBxW8X90CryJTJ2BVEz/ZQtn4aiFfvBewM0BBMgnUXj4J74vcAj
3AMyLCMPLZv4OkKv9gNP77OKsF3al/Q1cGvjhx+H3KMREc7Q2lXpeZ03ReqpC6YK
JnaGq6E70LmC1bv0pEhF8vtq90uRD4M1YYdFf0yCwFOHeJz4Is8q7fsr/7oGyim1
+pt3jAvnmjR79cpaqa9WNnrDjVVV5EC3yymU6ucCAwEAAaNTMFEwHQYDVR0OBBYE
FGdM9XXI/KGF4TV8Z0RPPoMKN9DzMB8GA1UdIwQYMBaAFGdM9XXI/KGF4TV8Z0RP
PoMKN9DzMA8GA1UdEwEB/wQFMAMBAf8wDQYJKoZIhvcNAQELBQADggEBAE9V4cfz
HsV5L72w0PrgjJMNgHB2bK98R0p/ie/bEBsTo+9RK0hygUxrQI/LKWWByJuf0EAC
vDn+BZOcL0RlRpEaenFSIIU8Yeh89oJ+31595wJ7zuSQb4/j6OfqCjnEqRtN4XYY
BfgNJTiWoSMwUOoT4AXU3aX8npcQWj6lZiHRbaGtNno7ipHIf1ZVFJ2vcg6oJfN1
7WnhIS75Kc4Plm3YpqXKL1ZqLNWCw/dBGQwYC6OfH7qraPpzOS4u+nO8zAr0wL4i
+Kli9X3ylGbKzM127PjjccSCE3fWCOaO71+h8LpZCBttnucw5SZaIZ2bX1bX4wxZ
aG2CdyvgqqKrQ5A=
-----END CERTIFICATE-----
"""


def der_control_truststore_secret() -> dict[str, dict]:
    """Placeholder Secrets Manager slot for der-control-ingress's mTLS
    truststore (the DERMS utility's CA bundle, PEM).

    Not `GenerateSecretString` (there's nothing to randomly generate here)
    and not a `!Ref` to a customer param (onboarding a real DERMS
    integration — which CA to trust — isn't part of the order-intake form
    today; that's a separate product decision). `aws secretsmanager
    put-secret-value` overwrites this with the real bundle once a specific
    integration is being stood up.
    """
    return {
        "DerControlTruststoreSecret": {
            "Type": "AWS::SecretsManager::Secret",
            "Properties": {
                "Name": {
                    "Fn::Sub": "arcnode-ems-${AWS::StackName}/der-control-truststore-pem"
                },
                "Description": (
                    "der-control-ingress mTLS truststore (DERMS CA bundle, "
                    "PEM). Placeholder — ops overwrites via PutSecretValue "
                    "per DERMS integration."
                ),
                "SecretString": _PLACEHOLDER_TRUSTSTORE_PEM,
            },
        },
    }


def auth_human_parameters() -> dict[str, dict]:
    """Two NoEcho String params — the customer's operator + viewer login pws.

    device-api bcrypt-hashes these at boot (it never stores plaintext at rest
    beyond secrets.env). NoEcho keeps them out of the Console + audit logs.
    """
    return {
        "AuthOperatorPw": {
            "Type": "String",
            "NoEcho": True,
            "MinLength": 1,
            "Description": "Operator login password (HMI dispatch role).",
        },
        "AuthViewerPw": {
            "Type": "String",
            "NoEcho": True,
            "MinLength": 1,
            "Description": "Viewer login password (HMI read-only role).",
        },
    }
