"""Setup wizard HTTP controller — serves the wizard UI + its two API routes.

Standalone app (see main.py) — not mounted into platform-api's own router,
a completely different deployment target (the appliance / an EC2 instance,
not platform-api's own running service).

Plain FastAPI APIRouter, not classy_fastapi's Routable (the convention used
elsewhere in this repo): the appliance runs this natively, installed via
apt (python3-fastapi) rather than Docker+pip, specifically so it has no
dependency on PyPI being reachable during provisioning. classy_fastapi has
no Debian package — see src/wizard/README.md for the full reasoning.
"""

from pathlib import Path
from typing import Final, Optional

from fastapi import APIRouter, HTTPException, status
from fastapi.responses import FileResponse, HTMLResponse

from src.wizard.wizard_record import ApplyRequest, ApplyResult, InstallIdentity
from src.wizard.wizard_service import WizardAlreadyAppliedError, WizardService

_STATIC_DIR: Final[Path] = Path(__file__).parent / "static"


class WizardController:
    """GET /setup (+ its static assets), GET /setup/api/identity, POST /setup/api/apply.

    ``install_identity_path`` points at install.json — written at ISO-build
    or AMI-launch time, read here, never generated by the wizard itself.
    """

    def __init__(self, *, service: WizardService, install_identity_path: Path) -> None:
        self._service = service
        self._install_identity_path = install_identity_path
        self.router = APIRouter()
        self.router.add_api_route(
            "/setup",
            self.index,
            methods=["GET"],
            summary="Serve the wizard UI, or 404 once applied",
        )
        self.router.add_api_route(
            "/setup/{filename}",
            self.static_asset,
            methods=["GET"],
            summary="Serve a static JSX/JS asset the UI references",
        )
        self.router.add_api_route(
            "/setup/api/identity",
            self.identity,
            methods=["GET"],
            summary="Read-only install identity for step 1",
        )
        self.router.add_api_route(
            "/setup/api/apply",
            self.apply,
            methods=["POST"],
            response_model=ApplyResult,
            summary="Write secrets.env + TLS, then disable this wizard for good",
        )

    async def index(self) -> HTMLResponse:
        """Entry point the operator's browser loads."""
        self._refuse_if_applied()
        return HTMLResponse((_STATIC_DIR / "index.html").read_text())

    async def static_asset(self, filename: str) -> FileResponse:
        """tokens.jsx / setup-wizard.jsx — whatever index.html's script tags need.

        FastAPI path params can't contain "/", so this only ever matches
        single-segment filenames — safe against path traversal without
        extra validation.
        """
        self._refuse_if_applied()
        path = _STATIC_DIR / filename
        if not path.is_file():
            raise HTTPException(status.HTTP_404_NOT_FOUND)
        return FileResponse(path)

    async def identity(self) -> Optional[InstallIdentity]:
        """None if install.json isn't there yet — the UI shows a loading state."""
        self._refuse_if_applied()
        if not self._install_identity_path.is_file():
            return None
        return InstallIdentity.model_validate_json(
            self._install_identity_path.read_text()
        )

    async def apply(self, request: ApplyRequest) -> ApplyResult:
        """The one irreversible action — see WizardService.apply's own docstring."""
        try:
            return self._service.apply(request)
        except WizardAlreadyAppliedError as exc:
            raise HTTPException(status.HTTP_404_NOT_FOUND, detail=str(exc)) from exc

    def _refuse_if_applied(self) -> None:
        if self._service.is_applied():
            raise HTTPException(
                status.HTTP_404_NOT_FOUND, detail="setup already applied"
            )
