"""Setup wizard HTTP controller — serves the wizard UI + its two API routes.

Standalone app (see main.py) — not mounted into platform-api's own router,
a completely different deployment target (the appliance / an EC2 instance,
not platform-api's own running service).
"""

from pathlib import Path
from typing import Final, Optional

from classy_fastapi import Routable, get, post
from fastapi import HTTPException, status
from fastapi.responses import FileResponse, HTMLResponse

from src.wizard.wizard_record import ApplyRequest, ApplyResult, InstallIdentity
from src.wizard.wizard_service import WizardAlreadyAppliedError, WizardService

_STATIC_DIR: Final[Path] = Path(__file__).parent / "static"


class WizardController(Routable):
    """GET /setup (+ its static assets), GET /setup/api/identity, POST /setup/api/apply.

    ``install_identity_path`` points at install.json — written at ISO-build
    or AMI-launch time, read here, never generated by the wizard itself.
    """

    def __init__(self, *, service: WizardService, install_identity_path: Path) -> None:
        super().__init__()
        self._service = service
        self._install_identity_path = install_identity_path

    @get("/setup", summary="Serve the wizard UI, or 404 once applied")
    async def index(self) -> HTMLResponse:
        """Entry point the operator's browser loads."""
        self._refuse_if_applied()
        return HTMLResponse((_STATIC_DIR / "index.html").read_text())

    @get("/setup/{filename}", summary="Serve a static JSX/JS asset the UI references")
    async def static_asset(self, filename: str) -> FileResponse:
        """tokens.jsx / setup-wizard.jsx — whatever index.html's script tags need.

        FastAPI path params can't contain "/", so this only ever matches
        single-segment filenames — safe against path traversal without
        extra validation.
        """
        self._refuse_if_applied()
        path = _STATIC_DIR / filename
        if not path.is_file():
            raise HTTPException(status.HTTP_404_NOT_FOUND)
        return FileResponse(path)

    @get(
        "/setup/api/identity",
        summary="Read-only install identity for step 1",
    )
    async def identity(self) -> Optional[InstallIdentity]:
        """None if install.json isn't there yet — the UI shows a loading state."""
        self._refuse_if_applied()
        if not self._install_identity_path.is_file():
            return None
        return InstallIdentity.model_validate_json(
            self._install_identity_path.read_text()
        )

    @post(
        "/setup/api/apply",
        response_model=ApplyResult,
        summary="Write secrets.env + TLS, then disable this wizard for good",
    )
    async def apply(self, request: ApplyRequest) -> ApplyResult:
        """The one irreversible action — see WizardService.apply's own docstring."""
        try:
            return self._service.apply(request)
        except WizardAlreadyAppliedError as exc:
            raise HTTPException(status.HTTP_404_NOT_FOUND, detail=str(exc)) from exc

    def _refuse_if_applied(self) -> None:
        if self._service.is_applied():
            raise HTTPException(
                status.HTTP_404_NOT_FOUND, detail="setup already applied"
            )
